name: ls_test_flutter_app
description: A new Flutter application.


dependencies:
  flutter:
    sdk: flutter

  http: '>=0.11.3+16'

  cupertino_icons: ^0.1.0

dev_dependencies:
#  flutter_test:
#    sdk: flutter

  json_serializable: "^0.5.6"

flutter:

  uses-material-design: true

